spring:
  config:
    import:
      - optional:nacos:order-service.yaml?group=user

  cloud:
    nacos:
      config:
        namespace: dev-namespace-id
      discovery:
        namespace: dev-namespace-id
        metadata:
          env: dev