spring:
  profiles:
    active: dev
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.server-addr:localhost:8848}
        username: ${nacos.username:nacos}
        password: ${nacos.password:nacos}
        namespace: ${nacos.namespace:dev-namespace-id}
      config:
        server-addr: ${nacos.server-addr:localhost:8848}
        username: ${nacos.username:nacos}
        password: ${nacos.password:nacos}
        namespace: ${nacos.namespace:dev-namespace-id}
        group: ${nacos.group:DEFAULT_GROUP}

logging:
  level:
    com.alibaba.cloud.nacos: DEBUG